test-warnings: true
doc-warnings: true
ignore-paths:
  - marmoset/virt/
uses:
  - flask
pep257:
  run: true
  disable:
    - D203
pep8:
  run: true
  full: true
pyroma:
  run: true
pylint:
  run: true
  enable:
    - unused-variable
    - invalid-name
dodgy:
  run: true
mccabe:
  run: true
