---
sudo: required
dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
before_install:
  - sudo apt-get update -q
  - sudo apt-get -y install libvirt-bin libvirt-dev
install:
  - pip install tox
script:
  - tox -e lint
notifications:
  irc:
    on_success: change
    on_failure: always
    skip_join: true
    channels:
      - "irc.freenode.org#virtapi"
  email: false
